version: '3.1'

services:
  babel:
    image: ee_node_tools
    build:
      context: .
    command: npx babel themes/ee/asset/javascript/src/ --watch -x ".es6" --out-dir themes/ee/asset/javascript/src/
    volumes:
      - .:/opt/app:delegated
      - /opt/app/node_modules # Prevent local node_modules from being mounted
