name: Run Cypress Content Tests

on:
  push:
    branches:
      - feature/cypress-tests
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - stability

jobs:
    cypress-tests:
        if: github.event.pull_request.draft == false
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                php: [7.3]
                os: [ubuntu-18.04]

        name: PHP${{ matrix.php }} - ${{ matrix.os }}

        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, sqlite, libxml, mbstring, zip, pcntl, pdo, mysql, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Copy config.php
              run: php -r "file_exists('system/user/config/config.php') || copy('tests/cypress/support/config.php', 'system/user/config/config.php');"

            - name: Setup Permissions
              run: |
                cp tests/docker/EllisLabUpdate.pub system/ee/EllisLab/ExpressionEngine
                sudo chmod 666 system/user/config/config.php
                sudo chmod 777 system/user/config
                sudo chmod -R 777 system/user/cache
                sudo chmod -R 777 system/user/templates
                sudo chmod -R 777 system/user/language
                sudo chmod -R 777 tests/rspec/support/tmp
                sudo chmod -R 777 tests/rspec/support/file-sync/uploads
                sudo chmod -R 777 images
                sudo chmod -R 777 themes/user
                cp themes/ee/asset/javascript/src/react/react.min.js themes/ee/asset/javascript/src/react/react.min~orig.js
                cat tests/rspec/shim.min.js themes/ee/asset/javascript/src/react/react.min.js > themes/ee/asset/javascript/src/react/react.min-shimmed.js
                mv themes/ee/asset/javascript/src/react/react.min-shimmed.js themes/ee/asset/javascript/src/react/react.min.js

            - name: Configure MySQL
              run: |
                sudo systemctl start mysql
                mysql -u root -proot -e 'CREATE DATABASE `ee-test`;'
                mysql -u root -proot -e 'SET GLOBAL sql_mode="ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION";'

            - name: Install PHP dependencies
              working-directory: tests/cypress
              run: composer install

            - name: Start PHP Server
              run: php -S localhost:8888 &

            - name: Run Cypress Tests
              uses: cypress-io/github-action@v1
              with:
                browser: chrome
                headless: true
                working-directory: tests/cypress
                config-file: content.cypress.json

            - name: Archive screenshots
              uses: actions/upload-artifact@v1
              if: failure()
              with:
                name: cypress-tests
                path: tests/cypress/cypress/screenshots/
