name: Run PHP Tests

on:
  push:
    branches:
      - testing/ee6-unit-testing
      - testing/php8
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - release/6.0.0

jobs:
    php-tests:
        if: github.event.pull_request.draft == false
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                php: [7.3, 7.4, 8.0]
                os: [ubuntu-latest]

        name: P${{ matrix.php }} - ${{ matrix.os }}

        steps:
            - name: Install locales
              run: |
                sudo locale-gen en
                sudo locale-gen de
                sudo locale-gen de_DE
                sudo locale-gen uk
                sudo locale-gen ru

            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, sqlite, libxml, mbstring, zip, pcntl, pdo, mysql, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Copy config.php
              run: php -r "file_exists('system/user/config/config.php') || copy('tests/docker/config.php', 'system/user/config/config.php');"

            - name: Install PHP dependencies
              working-directory: system/ee/ExpressionEngine/Tests/
              run: |
                composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-interaction
                composer require overtrue/phplint --dev --no-progress --no-suggest --prefer-dist

            - name: Run PHPLint
              run: ./system/ee/ExpressionEngine/Tests/vendor/bin/phplint ./ --exclude=system/ee/ExpressionEngine/Tests/vendor --exclude=system/ee/installer/config/config_tmpl.php

            - name: Run PHPUnit Tests
              working-directory: system/ee/ExpressionEngine/Tests/
              run: vendor/bin/phpunit --configuration=phpunit.xml

            - name: Install PHP dependencies for updater tests
              working-directory: system/ee/installer/updater/ExpressionEngine/Tests/
              run: |
                composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-interaction

#            - name: Run Updater PHPUnit Tests
#              working-directory: system/ee/installer/updater/ExpressionEngine/Tests/
#              run: vendor/bin/phpunit --configuration=phpunit.xml
